paths:
  /api/studentpost:
    post:
      tags:
        - Student Posts
      summary: Create a new student post
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                content:
                  type: string
      responses:
        201:
          description: Post created successfully
    
    get:
      tags:
        - Student Posts
      summary: Get all student posts
      responses:
        200:
          description: List of all student posts

  /api/studentpost/{id}:
    get:
      tags:
        - Student Posts
      summary: Get a student post by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        200:
          description: Student post found
        404:
          description: Student post not found

    put:
      tags:
        - Student Posts
      summary: Update a student post
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                content:
                  type: string
      responses:
        200:
          description: Post updated successfully
        404:
          description: Post not found

    delete:
      tags:
        - Student Posts
      summary: Delete a student post
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        200:
          description: Post deleted successfully
        404:
          description: Post not found 